--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: devops-project
  name: project-deployment
spec: 
  ports: ~
  replicas: 3
  selector: 
    matchLabels: 
      app: devops-project
  template: 
    metadata: 
      labels: 
        app: devops-project
    spec: 
      containers: 
        - 
          image: "afokepeniel/devops-project:version1.0"
          name: mywebpages

